version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo "Build Docker image..."
      - docker build -t $ECR_REPO .

  post_build:
    commands:
      - echo "Tag image..."
      - docker tag $ECR_REPO:latest $ECR_REGISTRY/$ECR_REPO:latest
      - echo "Push image to ECR..."
      - docker push $ECR_REGISTRY/$ECR_REPO:latest
